version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      svelte:
        patterns:
          - 'svelte*'
          - '@sveltejs/*'
      linting:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'typescript-eslint'
          - 'prettier*'
          - 'globals'
      vite:
        patterns:
          - 'vite*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
